import{a as L,i as w,S}from"./assets/vendor-C4-ZuMk8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const $="46065548-5ae4334dfe4b7f7d37f4bc842",E="https://pixabay.com/api/",P=15;async function m(r,t=1){const a=`${E}?key=${$}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${P}&page=${t}`;try{const n=await L.get(a);if(n.status!==200)throw new Error("Failed to fetch images");return n.data}catch(n){throw console.error("Error fetching images:",n),n}}const p=document.querySelector(".gallery");function h(r){const t=r.map(a=>q(a)).join("");p.insertAdjacentHTML("beforeend",t),_()}function q({webformatURL:r,largeImageURL:t,tags:a,likes:n,views:e,comments:o,downloads:i}){return`
    <a href="${t}" class="gallery__item">
      <img src="${r}" alt="${a}" loading="lazy" class="gallery__image" />
      <div class="info">
        <p><b>Likes:</b> ${n}</p>
        <p><b>Views:</b> ${e}</p>
        <p><b>Comments:</b> ${o}</p>
        <p><b>Downloads:</b> ${i}</p>
      </div>
    </a>
  `}function v(){p.innerHTML=""}function c(r){w.error({title:"Error",message:r})}let f;function _(){f?f.refresh():f=new S(".gallery a")}const I=document.querySelector("#search-form"),M=document.querySelector('input[name="searchQuery"]'),g=document.querySelector("#loader"),u=document.querySelector("#load-more");let s=1,l="",y=0;I.addEventListener("submit",O);u.addEventListener("click",C);async function O(r){if(r.preventDefault(),l=M.value.trim(),s=1,!l){c("Please enter a search query.");return}v(),b();try{const t=await m(l,s);if(d(),t.hits.length===0){c("Sorry, there are no images matching your search query. Please try again!"),u.style.display="none";return}y=t.totalHits,h(t.hits),u.style.display=s*15<y?"block":"none"}catch{d(),c("Failed to fetch images. Please try again later.")}}async function C(){s+=1,b();try{const r=await m(l,s);d(),h(r.hits),u.style.display=s*15<y?"block":"none";const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{d(),c("Failed to fetch more images. Please try again later.")}}function b(){g.style.display="block"}function d(){g.style.display="none"}
//# sourceMappingURL=index.js.map
